// Categories have two types:
// - 'identity': demographic filters that MODIFY topic searches (intersectional)
// - 'topic': content topics, can be combined with identity filters
//
// When identity + topic are selected together, queries are generated by combining
// identity terms with topic fragments — e.g. "pessoas negras tecnologia".

export const VIDEO_CATEGORIES = {
  // ── Identity / demographic ─────────────────────────────────────────────────
  'Personalidade Negra': {
    type: 'identity',
    terms: ['pessoas negras', 'black creators', 'negro negra'],
    standalone: [
      'criadores negros brasil',
      'personalidades negras',
      'representatividade negra conteúdo',
      'black creators brasileiros',
    ],
  },
  'Mulheres Empreendedoras': {
    type: 'identity',
    terms: ['mulheres', 'empreendedoras', 'criadoras mulheres'],
    standalone: [
      'empreendedoras brasileiras',
      'mulheres nos negócios brasil',
      'criadora de conteúdo mulher',
      'mulheres tech brasil',
    ],
  },

  // ── Topic ─────────────────────────────────────────────────────────────────
  'Finanças': {
    type: 'topic',
    queries: ['investimentos 2026', 'renda extra brasil', 'educação financeira'],
    fragment: 'finanças e investimentos',
  },
  'Tech': {
    type: 'topic',
    queries: ['inteligência artificial', 'startups brasil', 'programação web'],
    fragment: 'tecnologia',
  },
  'Marketing': {
    type: 'topic',
    queries: ['marketing digital', 'crescimento instagram', 'copywriting'],
    fragment: 'marketing digital',
  },
  'Lifestyle': {
    type: 'topic',
    queries: ['produtividade', 'rotina matinal', 'saúde mental criador'],
    fragment: 'lifestyle e bem-estar',
  },
  'Empreendedorismo': {
    type: 'topic',
    queries: ['empreendedorismo brasil', 'negócio online', 'escalar negócio'],
    fragment: 'empreendedorismo',
  },
  'Criação de Conteúdo': {
    type: 'topic',
    queries: ['crescer nas redes sociais', 'algoritmo 2026', 'monetização conteúdo'],
    fragment: 'criação de conteúdo',
  },
}

export const CATEGORY_NAMES     = Object.keys(VIDEO_CATEGORIES)
export const IDENTITY_CATEGORIES = CATEGORY_NAMES.filter((k) => VIDEO_CATEGORIES[k].type === 'identity')
export const TOPIC_CATEGORIES    = CATEGORY_NAMES.filter((k) => VIDEO_CATEGORIES[k].type === 'topic')

// Build search query pairs from selected categories.
// With identity + topic selected, returns intersectional queries like
// "pessoas negras tecnologia" instead of separate searches.
export function queriesForCategories(categories) {
  const defs = categories
    .map((c) => ({ name: c, ...VIDEO_CATEGORIES[c] }))
    .filter((d) => d.type)

  const identities = defs.filter((d) => d.type === 'identity')
  const topics     = defs.filter((d) => d.type === 'topic')

  const seen = new Set()
  const out  = []

  function add(category, query) {
    const key = `${category}::${query}`
    if (seen.has(key)) return
    seen.add(key)
    out.push({ category, query })
  }

  if (identities.length === 0) {
    // Pure topic search — original behavior
    for (const topic of topics) {
      for (const query of (topic.queries || [])) add(topic.name, query)
    }
  } else if (topics.length === 0) {
    // Pure identity search — use standalone queries
    for (const identity of identities) {
      for (const query of (identity.standalone || [])) add(identity.name, query)
    }
  } else {
    // Intersectional: combine identity terms with topic fragments
    for (const identity of identities) {
      for (const topic of topics) {
        const label = `${identity.name} × ${topic.name}`
        // e.g. "pessoas negras tecnologia", "black creators tecnologia"
        for (const term of (identity.terms || []).slice(0, 2)) {
          add(label, `${term} ${topic.fragment}`)
        }
        // Also combine primary identity term with the topic's first specific query
        const topicQuery     = (topic.queries || [])[0]
        const identityTerm   = (identity.terms || [])[0]
        if (topicQuery && identityTerm) add(label, `${identityTerm} ${topicQuery}`)
      }
    }
  }

  return out
}
